var data=[
    {
        "name":"HHSOJ Web Edition",
        "link":"https://github.com/XiaoGeNintendo/HHSOJ-Web-Edition",
        "author":"XGN",
        "release":"2018-09-12",
        "coauthor":"Zzzyt,XIZCM",
        "category":"OI",
        "subcategory":"OI SOFTWARE",
        "status":"Working",
        "lang":"Java,C++,etc.",
        "rating":4
    },
    {
        "name":"THHHS",
        "link":"http://blog.hellholestudios.club/post/2019/05/25/%E6%9D%B1%E6%96%B9%E5%9C%B0%E7%8D%84%E6%B4%9E%E6%96%87%E6%A1%A3touhou-shining-heroes-in-deep-dark-hole/",
        "author":"XGN",
        "release":"2019-05-25",
        "coauthor":"Zzzyt,WZZ",
        "category":"GAME",
        "subcategory":"STG GAME",
        "status":"Working",
        "lang":"LuaStg",
        "rating":2
    },
    {
        "name":"Rocket Simulator",
        "link":"https://github.com/Zzzzzzyt/RocketSimulator",
        "author":"Zzzyt",
        "release":"2019-06-13",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"SIM GAME",
        "status":"Working",
        "lang":"LibGdx",
        "rating":2
    },
    {
        "name":"Test STG2",
        "link":"https://github.com/XiaoGeNintendo/-LibGdx-Test-STG2",
        "author":"XGN",
        "release":"2019-07-01",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"STG GAME",
        "status":"Working",
        "lang":"LibGdx",
        "rating":1
    },
    {
        "name":"Codeforces Submission Reviewer",
        "link":"https://github.com/XiaoGeNintendo/Codeforces-Submission-Reviewer",
        "author":"XGN",
        "release":"2018-12-31",
        "coauthor":"",
        "category":"OI",
        "subcategory":"OI TOOL",
        "status":"Done",
        "lang":"JS,HTML",
        "rating":2
    },
    {
        "name":"Touhou Music Fetcher",
        "link":"https://github.com/XiaoGeNintendo/TouhouMusicFetcher",
        "author":"XGN",
        "release":"2019-06-20",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"TOOL",
        "status":"Done",
        "lang":"Java",
        "rating":1
    },
    {
        "name":"Codeforces Data Copier",
        "link":"https://github.com/XiaoGeNintendo/CodeforcesDataCopier",
        "author":"XGN",
        "release":"2019-06-08",
        "coauthor":"",
        "category":"OI",
        "subcategory":"OI TOOL",
        "status":"Done",
        "lang":"Py3",
        "rating":1
    },
    {
        "name":"Pokemon Gif Fetcher",
        "link":"https://github.com/XiaoGeNintendo/PokemonGifFetcher",
        "author":"XGN",
        "release":"2019-06-08",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"TOOL",
        "status":"Done",
        "lang":"Py3",
        "rating":1
    },
    {
        "name":"Lua STG Fix",
        "link":"https://github.com/XiaoGeNintendo/LuaStgPlusFix",
        "author":"XGN",
        "release":"2019-06-07",
        "coauthor":"",
        "category":"MOD",
        "subcategory":"SOFTWARE MOD",
        "status":"Done",
        "lang":"Lua",
        "rating":0
    },
    {
        "name":"CPP Confusor",
        "link":"https://github.com/XiaoGeNintendo/cpp-confusor",
        "author":"XGN",
        "release":"2019-04-15",
        "coauthor":"",
        "category":"OI",
        "subcategory":"OI TOOL",
        "status":"Done",
        "lang":"C++",
        "rating":2
    },
    {
        "name":"Universe Model",
        "link":"https://github.com/Zzzzzzyt/UniverseModel",
        "author":"Zzzyt",
        "release":"2019-05-08",
        "coauthor":"",
        "category":"MATH/PHYSICS",
        "subcategory":"PHYSICS SIMULATOR",
        "status":"Done",
        "lang":"LibGdx",
        "rating":0
    },
    {
        "name":"Paper Scissor Stone",
        "link":"https://github.com/Zzzzzzyt/PaperScissorStone",
        "author":"Zzzyt",
        "release":"2019-02-14",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"Java",
        "rating":0
    },
    {
        "name":"General Mod Loader",
        "link":"https://github.com/Zzzzzzyt/General-ModLoader",
        "author":"Zzzyt",
        "release":"2018-05-11",
        "coauthor":"",
        "category":"DEVELOP",
        "subcategory":"JAVA PACKAGE",
        "status":"Done",
        "lang":"Java",
        "rating":2
    },
    {
        "name":"ZJSTG",
        "link":"https://github.com/Zzzzzzyt/ZJSTG",
        "author":"HDD",
        "release":"2018-10-06",
        "coauthor":"Zzzyt",
        "category":"GAME",
        "subcategory":"STG GAME",
        "status":"Deserted",
        "lang":"GameMaker",
    },
    {
        "name":"ZYTALE",
        "link":"https://github.com/Zzzzzzyt/ZYTALE",
        "author":"Zzzyt",
        "release":"2018-03-11",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"RPG GAME",
        "status":"Deserted",
        "lang":"GameMaker",
    },
    {
        "name":"Hell Hole Legend",
        "link":"",
        "author":"XGN",
        "release":"2018-07-08",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"RPG GAME",
        "status":"Done",
        "lang":"RPG Maker XP",
        "comment":"Can't upload because of privacy issues",
    },
    {
        "name":"Slap",
        "link":"https://blog.hellholestudios.club/post/2019/05/12/%E8%B6%99%E9%8E%B9%E5%9C%A3%E6%85%95%E5%B2%AD%EF%BD%9Ecircle-cycling-circumstance%EF%BD%9E/",
        "author":"XGN",
        "release":"2019-05-12",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"ADV GAME",
        "status":"Deserted",
        "lang":"LibGdx",
    },
    {
        "name":"Slap v1.1",
        "link":"https://blog.hellholestudios.club/post/2019/05/19/slap-1-1-release/",
        "author":"XGN",
        "release":"2019-05-19",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"ADV GAME",
        "status":"Deserted",
        "lang":"LibGdx",
        "rating":3
    },
    {
        "name":"Netease Music Downloader",
        "link":"https://github.com/DamnXIZCM/netease-music-download",
        "author":"XIZCM",
        "release":"2019-03-27",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"TOOL",
        "status":"Done",
        "lang":"Py3",
        "rating":1
    },
    {
        "name":"Codeforces Telegram Notifier",
        "link":"https://github.com/DamnXIZCM/Codeforces-telegram-notifier",
        "author":"XIZCM",
        "release":"2019-06-08",
        "coauthor":"",
        "category":"BOT",
        "subcategory":"TELEGRAM BOT",
        "status":"Done",
        "lang":"Py3",
        "rating":1
    },
    {
        "name":"Testbot",
        "link":"https://repl.it/@XiaoGeNintendo/Test-js-bot",
        "author":"XGN",
        "release":"2019-02-15",
        "coauthor":"",
        "category":"BOT",
        "subcategory":"DISCORD BOT",
        "status":"Jamming",
        "lang":"Node.js",
        "comment":"The bot is used in our Discord community",
        "rating":2
    },
    {
        "name":"Orange Boy Can You Solve It Out?",
        "link":"https://blog.hellholestudios.club/post/tag/obcysio/",
        "author":"XGN",
        "release":"2019-04-14",
        "coauthor":"MonkeyKing",
        "category":"LITERATURE",
        "subcategory":"OI LITERATURE",
        "status":"Working",
        "lang":"Markup",
        "rating":4
    },
    {
        "name":"The Story of Tengfei",
        "link":"https://blog.hellholestudios.club/post/category/%E8%BF%9E%E8%BD%BD%E5%86%85%E5%AE%B9/",
        "author":"XGN",
        "release":"2019-04-10",
        "coauthor":"",
        "category":"LITERATURE",
        "subcategory":"OTHER LITERATURE",
        "status":"Deserted",
        "lang":"Markup",
        "rating":2
    },
    {
        "name":"Sound Guess Game",
        "link":"https://github.com/XiaoGeNintendo/SoundGuessGame",
        "author":"XGN",
        "release":"2019-02-13",
        "coauthor":"Zzzyt",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"Java",
        "rating":2
    },
    {
        "name":"Sound Guess Game Pokemon Mod",
        "link":"https://github.com/XiaoGeNintendo/SoundGuessGamePokemonMod",
        "author":"XGN",
        "release":"2019-02-13",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"Java",
        "rating":1
    },
    {
        "name":"Sound Guess Game HHS Mod",
        "link":"",
        "author":"Zzzyt",
        "release":"2019-02-16",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"Java",
        "comment":"Can't upload because of privacy issues.",
        "rating":2
    },
    {
        "name":"LibLrc",
        "link":"https://github.com/XiaoGeNintendo/LibLrc",
        "author":"XGN",
        "release":"2019-02-09",
        "coauthor":"",
        "category":"DEVELOP",
        "subcategory":"JAVA LIBRARY",
        "status":"Done",
        "lang":"Java",
        "rating":0
    },
    {
        "name":"HHS Project Site",
        "link":"https://github.com/HellHoleStudios/HHS-Project-Site",
        "author":"XGN",
        "release":"2019-07-22",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"HHS HOME",
        "status":"Working",
        "lang":"JS,HTML",
        "rating":4
    },
	{
        "name":"Addon Tools",
        "link":"https://github.com/XiaoGeNintendo/addon-tools",
        "author":"XGN",
        "release":"2017-12-25",
        "coauthor":"",
        "category":"MOD",
        "subcategory":"MINECRAFT MOD",
        "status":"Jamming",
        "lang":"Java",
        "comment":"'Jamming' means is updating slowly.",
        "rating":1
    },
	{
        "name":"NFLS Solution Getter",
        "link":"https://github.com/XiaoGeNintendo/NFLSOJ-Solution-Getter",
        "author":"XGN",
        "release":"2019-06-07",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"TOOL",
        "status":"Done",
        "lang":"Py3",
        "comment":"Doesn't work anymore because NFLSOJ system update.",
        "rating":0
    },
	{
        "name":"Pressing Competition",
        "link":"https://github.com/XiaoGeNintendo/PressingCompetition",
        "author":"XGN",
        "release":"2018-12-27",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"JS,HTML",
        "rating":2
    },
	{
        "name":"Many Notifier",
        "link":"https://github.com/XiaoGeNintendo/ManyNotifier",
        "author":"XGN",
        "release":"2018-07-19",
        "coauthor":"Zzzyt",
        "category":"OI",
        "subcategory":"OI TOOL",
        "status":"Done",
        "lang":"Java",
        "rating":3
    },
	{
        "name":"Codeforces Status Notifier",
        "link":"https://github.com/XiaoGeNintendo/Codeforces-Status-Notifier",
        "author":"Zzzyt",
        "release":"2018-07-14",
        "coauthor":"XGN",
        "category":"OI",
        "subcategory":"OI TOOL",
        "status":"Done",
        "lang":"Java",
        "rating":0
    },
	{
        "name":"Where're my scores",
        "link":"https://github.com/XiaoGeNintendo/Where-are-my-scores-",
        "author":"XGN",
        "release":"2018-05-27",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"MUSIC GAME",
        "status":"Done",
        "lang":"LibGdx",
        "rating":0
    },
	{
        "name":"NFLS Rating System",
        "link":"https://github.com/XiaoGeNintendo/NFLS-OJ-Club-Contest-Rating-System",
        "author":"XGN",
        "release":"2018-03-01",
        "coauthor":"",
        "category":"OI",
        "subcategory":"OI TOOL",
        "status":"Done",
        "lang":"Java",
        "rating":1
    },
	{
        "name":"Math Exam Simulator Online",
        "link":"https://github.com/XiaoGeNintendo/MathExamSimulatorOnline",
        "author":"XGN",
        "release":"2018-05-12",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"SIM GAME",
        "status":"Done",
        "lang":"CocosCreator",
        "rating":0
    },
	{
        "name":"YP Beating Me",
        "link":"https://github.com/XiaoGeNintendo/YPBeatingMe",
        "author":"XGN",
        "release":"2018-05-06",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"STG GAME",
        "status":"Done",
        "lang":"CocosCreator",
        "rating":3
    },
	{
        "name":"XGN Screen Gif Gen",
        "link":"https://github.com/XiaoGeNintendo/xgn-screen-gif-gen",
        "author":"XGN",
        "release":"2018-04-20",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"TOOL",
        "status":"Done",
        "lang":"Java",
        "rating":1
    },
	{
        "name":"HHSOJ",
        "link":"https://github.com/XiaoGeNintendo/hhsoj",
        "author":"XGN",
        "release":"2018-03-26",
        "coauthor":"",
        "category":"OI",
        "subcategory":"ONLINE JUDGE",
        "status":"Done",
        "lang":"Java",
        "comment":"This version is replaced by HHSOJ-Web-Edition",
    },
	{
        "name":"Osu Taiko to normal",
        "link":"https://github.com/XiaoGeNintendo/osu-taiko-2-normal",
        "author":"XGN",
        "release":"2018-03-29",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"TOOL",
        "status":"Done",
        "lang":"C++",
        "comment":"This tool should be worked with Osu"
    },
	{
        "name":"Upload and Download System",
        "link":"https://github.com/XiaoGeNintendo/Upload-and-Download-System",
        "author":"XGN",
        "release":"2018-03-11",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"LANGUAGE TEST",
        "status":"Done",
        "lang":"Java",
    },
	{
        "name":"ZJS vs YP",
        "link":"https://github.com/XiaoGeNintendo/ZJSvsYP",
        "author":"XGN",
        "release":"2018-06-07",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"CLICKING GAME",
        "status":"Done",
        "lang":"CocosCreator",
    },
	{
        "name":"Text Editor Reloaded",
        "link":"https://github.com/XiaoGeNintendo/text-editor-reloaded",
        "author":"XGN",
        "release":"2017-12-25",
        "coauthor":"",
        "category":"MISC",
        "subcategory":"LANGUAGE TEST",
        "status":"Done",
        "lang":"Java",
    },
	{
        "name":"3DZJS",
        "link":"https://github.com/HellHoleStudios/3D_ZJS",
        "author":"HDD",
        "release":"2018-03-11",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"GameMaker",
        "comment":"The link is empty. But it really has the name 3DZJS",
        "rating":2
    },
	{
        "name":"Planet ZJS",
        "link":"",
        "author":"XGN",
        "release":"2019-02-06",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"MonkeyEngine",
        "comment":"Download used to be ok in Skype, but now missing",
        "rating":2
    },
	{
        "name":"Number Game",
        "link":"https://drive.google.com/open?id=1R9qzZXMnT20j7L5HJzV5_WqOQMD1Srgt",
        "author":"XGN",
        "release":"2019-05-03",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"LibGdx",
        "rating":2
    },
    {
        "name":"YP vs ZJS",
        "link":"",
        "author":"XIZCM",
        "release":"",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"Py3",
    },
    {
        "name":"花泽香菜：救火(At the fire scene:putting out)",
        "link":"",
        "author":"XGN",
        "release":"",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"E",
        "rating":2
    },
    {
        "name":"破口大骂(Shout Abuse)",
        "link":"",
        "author":"HDD",
        "release":"",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"E",
    },
    {
        "name":"Steve Run With His Friends",
        "link":"https://mail.163.com/js6/read/readdata.jsp?sid=EAePnxbFStBlHOWofgFFxQljmRdockRS&mid=40:1tbiKBndnlEAO+4AlAACsg_5ec:232:h:b:g&part=3&mode=download&l=read&action=download_attach",
        "author":"XGN",
        "release":"2015-04-16",
        "coauthor":"Zzzyt",
        "category":"GAME",
        "subcategory":"RPG GAME",
        "status":"Done",
        "lang":"Scratch",
        "comment":"The date is not accurate because it's too old.The link gives you a 1.6 ver(quite old)",
        "rating":3
    },
    {
        "name":"花泽香菜(At the fire scene)",
        "link":"http://mail.163.com/js6/s?func=mbox:getMessageData&sid=EAePnxbFStBlHOWofgFFxQljmRdockRS&mid=289:xtbBIQUAACBvNGgTxD-4cn&part=3",
        "author":"Zzzyt",
        "release":"2017-02-04",
        "coauthor":"",
        "category":"GAME",
        "subcategory":"RPG GAME",
        "status":"Deserted",
        "lang":"VB",
        "rating":2,
        "comment":"The link only gives you the picture. As Zzzyt never released its game file"
    },
    {
        "name":"亡者农药(The dead game)",
        "link":"https://mail.163.com/js6/read/readpack.jsp?sid=EAePnxbFStBlHOWofgFFxQljmRdockRS&mid=519:xtbCBwYAACHhsg8j+h-hcb&part=3&part=4&part=5&part=6&part=7&part=8&part=9",
        "author":"XGN",
        "release":"2017-04-08",
        "coauthor":"Zzzyt",
        "category":"GAME",
        "subcategory":"OTHER GAME",
        "status":"Done",
        "lang":"E",
        "rating":3,
        "comment":"The link is 1.0 while 1.1 is missing"
    },
]
