var member=[
    {
        "name":"HDD292",
        "pic":"assets/HDD292.jpg",
		"badge":[
			"core","skype","discord"
		],
        "aka":"HDD, HJJ",
        "contact":[
			{
				"link":"https://github.com/HDD292",
				"display":"Github"
			}
        ]
    },
    {
        "name":"Zzzyt",
        "pic":"assets/Zzzyt.jpg",
		"badge":[
			"core","skype","discord"
		],
        "aka":"XiaoMao205, ZJS",
        "contact":[
            {
                "link":"https://codeforces.com/profile/zzzyt",
                "display":"Codeforces"
            },
            {
                "link":"https://github.com/Zzzzzzyt",
                "display":"Github"
            },
			{
				"link":"https://db.zzzyt.cf",
				"display":"Blog"
			}
        ]
    },
    {
        "name":"XiaoGeNintendo",
        "pic":"assets/XGN.jpg",
		"badge":[
			"core","skype","discord"
		],
        "aka":"XGN, gwq2017",
        "contact":[
            {
                "link":"https://codeforces.com/profile/gwq2017",
                "display":"Codeforces"
            },
            {
                "link":"https://codeforces.com/profile/I_love_hellholestudios",
                "display":"Codeforces2"
            },
            {
                "link":"https://github.com/XiaoGeNintendo",
                "display":"Github"
            }
        ]
    },
    {
        "name":"Carott",
        "pic":"assets/carott.jpg",
		"badge":[
			"core","skype","discord"
		],
        "aka":"IC, XZM, XIZCM",
        "contact":[
            {
                "link":"https://codeforces.com/profile/carott",
                "display":"Codeforces"
            },
            {
                "link":"https://github.com/carottX",
                "display":"Github"
            },
			{
				"link":"https://xizcm.site",
				"display":"Blog"
			}
        ]
    },
    {
        "name":"ZHD",
        "pic":"",
		"badge":[
			"main","skype"
		],
        "aka":"ZYD, ZHR, ZHDssss",
        "contact":[
            {
                "link":"https://codeforces.com/profile/bp_ZHD_qd",
                "display":"Codeforces"
            },
			{
				"link":"https://github.com/zhdssss",
				"display":"Github"
			}
        ]
    },
    {
        "name":"MonkeyKing",
        "pic":"assets/MonkeyKing.jpg",
		"badge":[
			"related","skype","discord"
		],
        "aka":"MK, Orange Boy",
        "contact":[
            {
                "link":"https://codeforces.com/profile/MonkeyKing",
                "display":"Codeforces"
            },
            {
                "link":"https://github.com/1839714778",
                "display":"Github"
            }
        ]
    },
    {
        "name":"Zhuky.RLG",
        "pic":"",
		"badge":[
			"main","skype"
		],
        "aka":"Zhuky, ZKY",
        "contact":[
            {
                "link":"https://codeforces.com/profile/ZhuKY.RLG",
                "display":"Codeforces"
            },
			{
				"link":"https://github.com/zhukyRLG",
				"display":"Github"
			}
        ]
    },
    {
        "name":"WZZ",
        "pic":"assets/WZZ.jpg",
		"badge":[
			"main","skype"
		],
        "aka":"WN",
        "contact":[
            {
                "link":"https://codeforces.com/profile/Hytedresorale_Toad",
                "display":"Codeforces"
            }
        ]
    },
    {
        "name":"HYK",
        "badge":[
			"branch","skype"
		],
        "pic":"",
        "aka":"",
        "contact":[
            
        ]
    },
    {
        "name":"SYR",
        "badge":[
			"related"
		],
        "pic":"https://userpic.codeforces.com/590414/title/17aff651ea848953.jpg",
        "aka":"Ling2Feng1,Mackerel Pike",
        "contact":[
            {
                "link":"https://codeforces.com/profile/Mackerel_Pike",
                "display":"Codeforces"
            }
        ]
    },
    {
        "name":"Denverjin",
        "badge":[
			"related"
		],
        "pic":"https://userpic.codeforces.com/282281/title/c8232938f829a097.jpg",
        "aka":"KillerX,jt,today",
        "contact":[
            {
                "link":"https://codeforces.com/profile/Denverjin",
                "display":"Codeforces"
            }
        ]
    },
    {
        "name":"Starcutter",
        "badge":[
			"related"
		],
        "pic":"",
        "aka":"gwb,XGN's younger brother",
        "contact":[
            {
                "link":"https://codeforces.com/profile/Starcutter",
                "display":"Codeforces"
            }
        ]
    },
    {
        "name":"guanhuai",
        "badge":[
			"related"
		],
        "pic":"https://userpic.codeforces.com/323356/title/319a1226511924f6.jpg",
        "aka":"gh",
        "contact":[
            {
                "link":"https://codeforces.com/profile/guanhuai04",
                "display":"Codeforces"
            }
        ]
    },
]

var badge={
	"skype":{
		"code":"badge badge-warning",
		"display":"Skype"
	},
	"discord":{
		"code":"badge badge-danger",
		"display":"Discord"
	},
    "core":{
        "code":"badge badge-success",
        "display":"Core Member"
    },
    "main":{
        "code":"badge badge-primary",
        "display":"Main Member"
    },
    "branch":{
        "code":"badge badge-secondary",
        "display":"Branch Member"
    },
    "related":{
        "code":"badge badge-info",
        "display":"Related People"
    },
}